{{ config(materialized='table') }}

with cases as (
  select distinct LOCATION_ISO_CODE ,
  to_Date(date,'mm/dd/yyyy'),
GROWTH_FACTOR_OF_NEW_DEATHS ,
	NEW_CASES_PER_MILLION ,
	POPULATION_DENSITY ,
	POPULATION ,
	NEW_DEATHS_PER_MILLION ,
	NEW_RECOVERED ,
	CASE_FATALITY_RATE ,
	NEW_DEATHS ,
	NEW_CASES ,
	DATE ,
	CASE_RECOVERED_RATE ,
	NEW_ACTIVE_CASES ,
	GROWTH_FACTOR_OF_NEW_CASES  from FIVETRAN_INTERVIEW_DB.GOOGLE_SHEETS.COVID_19_INDONESIA_PRADIPTA_SENGUPTA
)
select * from cases
